import { db } from "./index";
import { events, type NewEvent } from "./schema";

// NOTE: This seed file needs to be updated to create organizations first
// and link events to them via organizationId. Temporarily disabled.
// TODO: Create organizations table entries before creating events

// Manual seed data based on research of actual LATAM events
const seedEvents: NewEvent[] = [
  /* Temporarily disabled - needs organizationId

  {
    slug: "hackmty-2025",
    name: "HackMTY 2025",
    description:
      "Mexico's largest hackathon bringing together 1,000+ developers, designers, and entrepreneurs for 48 hours of innovation. Open to all skill levels with multiple sponsor tracks and prizes.",
    eventType: "hackathon",
    startDate: new Date("2025-08-15T09:00:00"),
    endDate: new Date("2025-08-17T18:00:00"),
    registrationDeadline: new Date("2025-08-01T23:59:59"),
    format: "in-person",
    country: "MX",
    city: "Monterrey",
    timezone: "America/Monterrey",
    skillLevel: "all",
    domains: ["ai", "fintech", "social-impact", "general"],
    prizePool: 50000,
    prizeDescription: "Multiple tracks with prizes from sponsors including AWS, Google, Microsoft",
    websiteUrl: "https://hackmty.com",
    registrationUrl: "https://hackmty2025.devpost.com",
    devpostUrl: "https://hackmty2025.devpost.com",
    eventImageUrl: "https://d112y698adiu2z.cloudfront.net/photos/production/challenge_thumbnails/002/897/234/datas/original.png",
    organizerName: "HackMTY",
    organizerUrl: "https://hackmty.com",
    status: "upcoming",
    isFeatured: true,
    isApproved: true,
  },
  {
    slug: "latam-wis-2025",
    name: "LATAM WIS Hackathon 2025",
    description:
      "Women in STEM hackathon across Latin America. A 3-day virtual event focused on empowering women in technology with mentorship, workshops, and innovation challenges.",
    eventType: "hackathon",
    startDate: new Date("2025-03-08T10:00:00"),
    endDate: new Date("2025-03-10T18:00:00"),
    registrationDeadline: new Date("2025-03-01T23:59:59"),
    format: "virtual",
    country: "LATAM",
    timezone: "America/Sao_Paulo",
    skillLevel: "all",
    domains: ["ai", "social-impact", "edtech"],
    prizePool: 5000,
    prizeDescription: "Scholarships, mentorship programs, and tech prizes",
    websiteUrl: "https://hackaton-latam-wis.devpost.com",
    registrationUrl: "https://hackaton-latam-wis.devpost.com",
    devpostUrl: "https://hackaton-latam-wis.devpost.com",
    organizerName: "Women in STEM LATAM",
    status: "upcoming",
    isFeatured: true,
    isApproved: true,
  },
  {
    slug: "stacks-latam-hackathon-2025",
    name: "Stacks LATAM Hackathon",
    description:
      "Build the future of Bitcoin with Stacks. 3-week virtual hackathon with in-person finale in Buenos Aires. Focus on DeFi, NFTs, and Web3 applications on Bitcoin.",
    eventType: "hackathon",
    startDate: new Date("2025-04-01T00:00:00"),
    endDate: new Date("2025-04-21T23:59:59"),
    registrationDeadline: new Date("2025-03-28T23:59:59"),
    format: "hybrid",
    country: "AR",
    city: "Buenos Aires",
    timezone: "America/Argentina/Buenos_Aires",
    skillLevel: "intermediate",
    domains: ["web3", "blockchain", "fintech"],
    prizePool: 25000,
    prizeDescription: "$3,000 USD first place + Hacker House trip to Buenos Aires",
    websiteUrl: "https://lu.ma/stacks-latam",
    registrationUrl: "https://lu.ma/stacks-latam",
    organizerName: "Stacks Foundation",
    organizerUrl: "https://stacks.co",
    status: "upcoming",
    isFeatured: true,
    isApproved: true,
  },
  {
    slug: "desafio-latam-2025",
    name: "Desafío LATAM 2025",
    description:
      "Oracle Cloud hackathon for Latin American developers. Build innovative solutions using Oracle Cloud Infrastructure with mentorship from Oracle engineers.",
    eventType: "hackathon",
    startDate: new Date("2025-05-15T09:00:00"),
    endDate: new Date("2025-05-30T18:00:00"),
    format: "virtual",
    country: "LATAM",
    timezone: "America/Mexico_City",
    skillLevel: "intermediate",
    domains: ["ai", "general"],
    prizePool: 10000,
    prizeDescription: "Oracle Cloud credits, certifications, and cash prizes",
    websiteUrl: "https://desafiolatam.com",
    registrationUrl: "https://desafiolatam.com/hackathon",
    organizerName: "Oracle LATAM",
    organizerUrl: "https://oracle.com",
    status: "upcoming",
    isApproved: true,
  },
  {
    slug: "codelaunch-latam-2025",
    name: "CodeLaunch LATAM 2025",
    description:
      "48-hour startup hackathon in Guadalajara. Pitch your startup idea, build an MVP, and compete for investment capital from top LATAM VCs.",
    eventType: "hackathon",
    startDate: new Date("2025-06-20T09:00:00"),
    endDate: new Date("2025-06-22T18:00:00"),
    registrationDeadline: new Date("2025-06-10T23:59:59"),
    format: "in-person",
    country: "MX",
    city: "Guadalajara",
    timezone: "America/Mexico_City",
    skillLevel: "advanced",
    domains: ["fintech", "ai", "general"],
    prizePool: 75000,
    prizeDescription: "$50,000+ investment capital + accelerator spots",
    websiteUrl: "https://codelaunch.com/latam",
    registrationUrl: "https://codelaunch.com/latam/apply",
    organizerName: "CodeLaunch",
    organizerUrl: "https://codelaunch.com",
    status: "upcoming",
    isFeatured: true,
    isApproved: true,
  },
  {
    slug: "latina-blockchain-hackathon-2025",
    name: "Latina Blockchain Hackathon",
    description:
      "Multi-track blockchain hackathon for Latin American developers. Build on Ethereum, Solana, Polkadot, and more with mentorship from leading Web3 projects.",
    eventType: "hackathon",
    startDate: new Date("2025-07-10T00:00:00"),
    endDate: new Date("2025-07-24T23:59:59"),
    registrationDeadline: new Date("2025-07-05T23:59:59"),
    format: "virtual",
    country: "LATAM",
    timezone: "America/Sao_Paulo",
    skillLevel: "intermediate",
    domains: ["web3", "blockchain", "fintech"],
    prizePool: 15000,
    prizeDescription: "$2,500 first place per track + ecosystem grants",
    websiteUrl: "https://latina-blockchain-hackathon.devpost.com",
    registrationUrl: "https://latina-blockchain-hackathon.devpost.com",
    devpostUrl: "https://latina-blockchain-hackathon.devpost.com",
    organizerName: "Latina Blockchain",
    status: "upcoming",
    isApproved: true,
  },
  {
    slug: "hackaton-banorte-2025",
    name: "Hackatón Banorte 2025",
    description:
      "Mexico's premier fintech hackathon sponsored by Banorte. Build the future of banking with APIs, open finance, and AI-powered financial solutions.",
    eventType: "hackathon",
    startDate: new Date("2025-09-05T09:00:00"),
    endDate: new Date("2025-09-07T18:00:00"),
    registrationDeadline: new Date("2025-08-25T23:59:59"),
    format: "hybrid",
    country: "MX",
    city: "Ciudad de México",
    timezone: "America/Mexico_City",
    skillLevel: "all",
    domains: ["fintech", "ai"],
    prizePool: 100000,
    prizeDescription: "Cash prizes + potential pilot programs with Banorte",
    websiteUrl: "https://banorte.com/hackathon",
    registrationUrl: "https://banorte.com/hackathon/registro",
    organizerName: "Banorte",
    organizerUrl: "https://banorte.com",
    status: "upcoming",
    isFeatured: true,
    isApproved: true,
  },
  {
    slug: "nasa-space-apps-brasil-2025",
    name: "NASA Space Apps Brasil 2025",
    description:
      "Brazilian edition of NASA's global hackathon. Use open NASA data to solve challenges in space exploration, earth science, and technology.",
    eventType: "hackathon",
    startDate: new Date("2025-10-04T09:00:00"),
    endDate: new Date("2025-10-06T18:00:00"),
    registrationDeadline: new Date("2025-09-30T23:59:59"),
    format: "hybrid",
    country: "BR",
    city: "São Paulo",
    timezone: "America/Sao_Paulo",
    skillLevel: "all",
    domains: ["ai", "climate", "general"],
    prizePool: 5000,
    prizeDescription: "Global finalist spots + NASA swag + local prizes",
    websiteUrl: "https://www.spaceappschallenge.org",
    registrationUrl: "https://www.spaceappschallenge.org/locations/sao-paulo",
    organizerName: "NASA",
    organizerUrl: "https://nasa.gov",
    status: "upcoming",
    isApproved: true,
  },
  {
    slug: "ethargentina-2025",
    name: "ETH Argentina 2025",
    description:
      "Ethereum hackathon in Buenos Aires. Build dApps, DeFi protocols, and Web3 infrastructure with the Argentine and global Ethereum community.",
    eventType: "hackathon",
    startDate: new Date("2025-11-14T09:00:00"),
    endDate: new Date("2025-11-16T18:00:00"),
    registrationDeadline: new Date("2025-11-01T23:59:59"),
    format: "in-person",
    country: "AR",
    city: "Buenos Aires",
    timezone: "America/Argentina/Buenos_Aires",
    skillLevel: "intermediate",
    domains: ["web3", "blockchain", "fintech"],
    prizePool: 30000,
    prizeDescription: "ETH prizes + grants from Ethereum Foundation",
    websiteUrl: "https://ethargentina.org",
    registrationUrl: "https://ethargentina.org/hackathon",
    organizerName: "ETH Argentina",
    organizerUrl: "https://ethargentina.org",
    status: "upcoming",
    isFeatured: true,
    isApproved: true,
  },
  {
    slug: "llama-impact-hackathon-latam-2025",
    name: "Llama Impact Hackathon LATAM",
    description:
      "Build AI applications with Llama and Meta's open-source models. Focus on social impact projects across Latin America with mentorship from Meta engineers.",
    eventType: "hackathon",
    startDate: new Date("2025-02-20T00:00:00"),
    endDate: new Date("2025-03-05T23:59:59"),
    registrationDeadline: new Date("2025-02-15T23:59:59"),
    format: "virtual",
    country: "LATAM",
    timezone: "America/Los_Angeles",
    skillLevel: "intermediate",
    domains: ["ai", "social-impact", "open-source"],
    prizePool: 20000,
    prizeDescription: "Cash prizes + Meta AI credits + potential showcase at F8",
    websiteUrl: "https://lablab.ai/event/llama-impact-latam",
    registrationUrl: "https://lablab.ai/event/llama-impact-latam",
    organizerName: "lablab.ai & Meta",
    organizerUrl: "https://lablab.ai",
    status: "upcoming",
    isApproved: true,
  },

  // =====================
  // PERU HACKATHONS 2025
  // =====================

  {
    slug: "ia-hackathon-peru-2025",
    name: "IA Hackathon Perú 2025",
    description:
      "24-hour AI hackathon in Lima bringing together developers, data scientists, and AI enthusiasts. Build innovative AI solutions with mentorship from industry experts. Hosted at Universidad Cayetano Heredia.",
    eventType: "hackathon",
    startDate: new Date("2025-11-29T09:00:00"),
    endDate: new Date("2025-11-30T18:00:00"),
    registrationDeadline: new Date("2025-11-28T23:59:59"),
    format: "in-person",
    country: "PE",
    city: "Lima",
    timezone: "America/Lima",
    skillLevel: "intermediate",
    domains: ["ai", "healthtech", "general"],
    prizePool: 5600, // CHF 5,000 ≈ USD 5,600
    prizeDescription: "CHF 5,000+ in prizes + incubation opportunities",
    websiteUrl: "https://www.peru.ai-hackathon.co",
    registrationUrl: "https://www.peru.ai-hackathon.co",
    organizerName: "AI Hackathon Peru",
    status: "ongoing",
    isFeatured: true,
    isApproved: true,
  },
  {
    slug: "ethereum-lima-2025",
    name: "Ethereum Lima Hackathon 2025",
    description:
      "Build the future of Web3 in Peru. Ethereum Lima brings together blockchain developers to create dApps, DeFi protocols, and innovative Web3 solutions. Part of the global Ethereum community.",
    eventType: "hackathon",
    startDate: new Date("2025-10-24T09:00:00"),
    endDate: new Date("2025-10-26T18:00:00"),
    registrationDeadline: new Date("2025-10-20T23:59:59"),
    format: "in-person",
    country: "PE",
    city: "Lima",
    timezone: "America/Lima",
    skillLevel: "intermediate",
    domains: ["web3", "blockchain", "fintech"],
    prizePool: 2000,
    prizeDescription: "ETH prizes + ecosystem grants + mentorship",
    websiteUrl: "https://taikai.network/ethereum-lima/hackathons/hackathon-eth-lima",
    registrationUrl: "https://taikai.network/ethereum-lima/hackathons/hackathon-eth-lima",
    organizerName: "Ethereum Lima",
    organizerUrl: "https://taikai.network/ethereum-lima",
    status: "ended",
    isApproved: true,
  },
  {
    slug: "hack4her-latam-2025",
    name: "Hack4Her LATAM 2025",
    description:
      "The largest hackathon for women in STEM across Latin America. A 48-hour event focused on empowering women developers with challenges in AI, sustainability, and social impact.",
    eventType: "hackathon",
    startDate: new Date("2025-06-14T09:00:00"),
    endDate: new Date("2025-06-15T18:00:00"),
    registrationDeadline: new Date("2025-06-10T23:59:59"),
    format: "hybrid",
    country: "LATAM",
    timezone: "America/Lima",
    skillLevel: "all",
    domains: ["ai", "social-impact", "climate"],
    prizePool: 3000,
    prizeDescription: "Cash prizes + mentorship + incubation programs",
    websiteUrl: "https://hack4her2025.devpost.com",
    registrationUrl: "https://hack4her2025.devpost.com",
    devpostUrl: "https://hack4her2025.devpost.com",
    organizerName: "Hack4Her / Arca Continental",
    status: "ended",
    isFeatured: true,
    isApproved: true,
  },
  {
    slug: "hackathon-latam-wis-peru-2025",
    name: "Hackathon LATAM WIS 2025",
    description:
      "Free virtual hackathon focused on gender equity with 7 challenge tracks. Open to women and allies across Latin America. Mentorship, workshops, and prizes.",
    eventType: "hackathon",
    startDate: new Date("2025-06-13T10:00:00"),
    endDate: new Date("2025-06-15T18:00:00"),
    registrationDeadline: new Date("2025-06-10T23:59:59"),
    format: "virtual",
    country: "LATAM",
    timezone: "America/Lima",
    skillLevel: "beginner",
    domains: ["social-impact", "edtech", "general"],
    prizePool: 0,
    prizeDescription: "Mentorship, certificates, and networking opportunities",
    websiteUrl: "https://hackaton-latam-wis.devpost.com",
    registrationUrl: "https://hackaton-latam-wis.devpost.com",
    devpostUrl: "https://hackaton-latam-wis.devpost.com",
    organizerName: "Women in STEM LATAM",
    status: "ended",
    isApproved: true,
  },
  {
    slug: "minedu-hackathon-peru-2025",
    name: "Hackathon MINEDU 2025",
    description:
      "Peru's Ministry of Education hackathon bringing together 204 students to revolutionize education with AI and robotics. Focus on STEAM education innovation.",
    eventType: "hackathon",
    startDate: new Date("2025-08-01T09:00:00"),
    endDate: new Date("2025-08-03T18:00:00"),
    format: "in-person",
    country: "PE",
    city: "Lima",
    timezone: "America/Lima",
    skillLevel: "beginner",
    domains: ["ai", "edtech", "general"],
    prizePool: 0,
    prizeDescription: "Recognition + robotics kits + educational resources",
    websiteUrl: "https://www.gob.pe/institucion/minedu/noticias/1220259",
    registrationUrl: "https://www.gob.pe/institucion/minedu",
    organizerName: "Ministerio de Educación del Perú",
    organizerUrl: "https://www.gob.pe/minedu",
    status: "ended",
    isApproved: true,
  },
  {
    slug: "ayni-hackathon-2024",
    name: "AYNI Hackathon Nacional 2024",
    description:
      "National hackathon in the framework of APEC Peru. Multi-city event (Lima, Arequipa, Trujillo) focused on innovation and technological collaboration. Organized by UPC.",
    eventType: "hackathon",
    startDate: new Date("2024-10-18T09:00:00"),
    endDate: new Date("2024-10-20T18:00:00"),
    format: "hybrid",
    country: "PE",
    city: "Lima, Arequipa, Trujillo",
    timezone: "America/Lima",
    skillLevel: "intermediate",
    domains: ["general", "social-impact", "fintech"],
    prizePool: 1500,
    prizeDescription: "Cash prizes + incubation + networking with APEC delegates",
    websiteUrl: "https://www.aynihackathon.com",
    registrationUrl: "https://ayni-hackathon.devpost.com",
    devpostUrl: "https://ayni-hackathon.devpost.com",
    organizerName: "UPC / APEC Peru",
    organizerUrl: "https://www.upc.edu.pe",
    status: "ended",
    isApproved: true,
  },
  {
    slug: "desafio-hackathon-ai-griculture-2024",
    name: "Desafío Hackathon AI-griculture 2024",
    description:
      "AI hackathon focused on agricultural innovation. Build solutions using AI to transform agriculture in Latin America. Virtual participation from Peru.",
    eventType: "hackathon",
    startDate: new Date("2024-08-15T09:00:00"),
    endDate: new Date("2024-08-30T23:59:59"),
    format: "virtual",
    country: "PE",
    timezone: "America/Lima",
    skillLevel: "intermediate",
    domains: ["ai", "climate", "general"],
    prizePool: 750,
    prizeDescription: "USD $750 + incubation program",
    websiteUrl: "https://desafiolatam.com",
    registrationUrl: "https://desafiolatam.com/hackathon",
    organizerName: "CIP / Desafío Latam",
    organizerUrl: "https://cipotato.org",
    status: "ended",
    isApproved: true,
  },
  {
    slug: "hackathon-lima-segura",
    name: "Hackathon Lima Segura",
    description:
      "Civic tech hackathon organized by the Municipality of Lima. Build solutions for citizen security, urban mobility, and smart city initiatives.",
    eventType: "hackathon",
    startDate: new Date("2025-03-15T09:00:00"),
    endDate: new Date("2025-03-17T18:00:00"),
    format: "in-person",
    country: "PE",
    city: "Lima",
    timezone: "America/Lima",
    skillLevel: "beginner",
    domains: ["social-impact", "mobile", "general"],
    prizePool: 0,
    prizeDescription: "Recognition + implementation opportunities with Municipalidad de Lima",
    websiteUrl: "https://aplicativos.munlima.gob.pe/public/hackaton-lima-segura/",
    registrationUrl: "https://aplicativos.munlima.gob.pe/public/hackaton-lima-segura/",
    organizerName: "Municipalidad de Lima",
    organizerUrl: "https://munlima.gob.pe",
    status: "upcoming",
    isApproved: true,
  },
  {
    slug: "techstars-startup-weekend-lima-2025",
    name: "Techstars Startup Weekend Lima 2025",
    description:
      "54-hour startup sprint in Lima. Pitch your idea, form a team, build an MVP, and present to investors. Perfect for aspiring entrepreneurs and first-time hackers.",
    eventType: "hackathon",
    startDate: new Date("2025-04-11T18:00:00"),
    endDate: new Date("2025-04-13T21:00:00"),
    registrationDeadline: new Date("2025-04-08T23:59:59"),
    format: "in-person",
    country: "PE",
    city: "Lima",
    timezone: "America/Lima",
    skillLevel: "beginner",
    domains: ["general", "fintech", "social-impact"],
    prizePool: 0,
    prizeDescription: "Mentorship + potential investment + Techstars network access",
    websiteUrl: "https://startupweekendlima.com",
    registrationUrl: "https://startupweekendlima.com",
    organizerName: "Techstars",
    organizerUrl: "https://www.techstars.com",
    status: "upcoming",
    isApproved: true,
  },
  {
    slug: "peru-fintech-forum-hackathon-2025",
    name: "Perú Fintech Forum Hackathon 2025",
    description:
      "Fintech-focused hackathon as part of Peru Fintech Forum. Build innovative financial solutions with a special track for women in fintech.",
    eventType: "hackathon",
    startDate: new Date("2025-09-20T09:00:00"),
    endDate: new Date("2025-09-22T18:00:00"),
    format: "hybrid",
    country: "PE",
    city: "Lima",
    timezone: "America/Lima",
    skillLevel: "intermediate",
    domains: ["fintech", "ai", "mobile"],
    prizePool: 5000,
    prizeDescription: "Cash prizes + fintech accelerator spots + investor meetings",
    websiteUrl: "https://www.perufintechforum.com/hackathon/",
    registrationUrl: "https://www.perufintechforum.com/hackathon/",
    organizerName: "Peru Fintech Forum",
    organizerUrl: "https://www.latamfintech.co",
    status: "upcoming",
    isFeatured: true,
    isApproved: true,
  },
  {
    slug: "codeon-2025",
    name: "CodeOn 2025",
    description:
      "Student tech conference and mini-hackathon at UTP Lima. Workshops, talks, and coding challenges for university students.",
    eventType: "conference",
    startDate: new Date("2025-10-25T09:00:00"),
    endDate: new Date("2025-10-25T20:00:00"),
    format: "in-person",
    country: "PE",
    city: "Lima",
    timezone: "America/Lima",
    skillLevel: "beginner",
    domains: ["general", "edtech"],
    prizePool: 0,
    prizeDescription: "Certificates + swag + networking",
    websiteUrl: "https://luma.com/codeon2025",
    registrationUrl: "https://luma.com/codeon2025",
    organizerName: "UTP Lima",
    organizerType: "university",
    isJuniorFriendly: true,
    status: "ended",
    isApproved: true,
  },

  // ==========================================
  // PERU HACKATHONS - Facebook Manual Scrape
  // ==========================================

  {
    slug: "hackathon-cip-lima-smart-chancay-2025",
    name: "Hackathon CIP Lima: Smart Chancay",
    description:
      "Hub Eco-Tecnológico con IA. Iniciativa del Colegio de Ingenieros del Perú que impulsa el talento, la innovación y soluciones inteligentes para el futuro del país. Los equipos finalistas presentarán sus soluciones en la Semana de la Ingeniería Nacional 2026.",
    eventType: "hackathon",
    startDate: new Date("2025-11-17T00:00:00"),
    endDate: new Date("2026-06-08T18:00:00"),
    registrationDeadline: new Date("2025-12-31T23:59:59"),
    format: "hybrid",
    country: "PE",
    city: "Lima",
    timezone: "America/Lima",
    skillLevel: "intermediate",
    domains: ["ai", "climate", "govtech"],
    prizePool: 0,
    prizeDescription: "Exposición en Semana de la Ingeniería Nacional 2026 + reconocimiento CIP",
    websiteUrl: "https://hackathon.ciplima.org.pe",
    registrationUrl: "https://hackathon.ciplima.org.pe",
    organizerName: "Colegio de Ingenieros del Perú - Consejo Departamental de Lima",
    organizerType: "ngo",
    organizerUrl: "https://ciplima.org.pe",
    isJuniorFriendly: false,
    status: "open",
    isFeatured: true,
    isApproved: true,
  },
  {
    slug: "eneisoft-hackathon-2025",
    name: "Hackathon ENEISOFT 2025 - Edición XV",
    description:
      "El evento donde las ideas se convierten en soluciones reales. Si te apasiona la tecnología, el software y la innovación, esta es tu oportunidad para crear, conectar y competir con los mejores talentos del país. Participan universidades, institutos y bootcamps de todo el Perú.",
    eventType: "hackathon",
    startDate: new Date("2025-11-20T09:00:00"),
    endDate: new Date("2025-11-22T18:00:00"),
    registrationDeadline: new Date("2025-11-15T23:59:59"),
    format: "in-person",
    country: "PE",
    city: "Lima",
    timezone: "America/Lima",
    skillLevel: "all",
    domains: ["general", "mobile", "ai"],
    prizePool: 0,
    prizeDescription: "Premios, mentorías y oportunidades únicas",
    websiteUrl: "https://eneisoft.pe",
    registrationUrl: "https://forms.gle/KgRaNDEnKYYmQoGX8",
    organizerName: "ENEISOFT",
    organizerType: "student_org",
    isJuniorFriendly: true,
    status: "ended",
    isApproved: true,
  },
  {
    slug: "escuela-computacion-cuantica-hackathon-2025",
    name: "Segunda Escuela Peruana de Computación Cuántica - Hackathon",
    description:
      "Programa intensivo de 7 días con clases, conferencias, laboratorios prácticos y Hackathon dedicados al estudio de la Computación Cuántica. Celebración oficial del Año Internacional de Ciencia y Tecnología Cuántica (IYQ). 100% gratuito y con certificado.",
    eventType: "summer_school",
    startDate: new Date("2025-12-01T09:00:00"),
    endDate: new Date("2025-12-07T17:00:00"),
    format: "virtual",
    country: "PE",
    timezone: "America/Lima",
    skillLevel: "intermediate",
    domains: ["quantum", "ai", "edtech"],
    prizePool: 0,
    prizeDescription: "Certificación gratuita + networking con expertos internacionales",
    websiteUrl: "https://quantumquipu.cc",
    registrationUrl: "https://quantumquipu.cc",
    organizerName: "QuantumQuipu / UNMSM / UNESCO",
    organizerType: "international_org",
    organizerUrl: "https://quantumquipu.cc",
    isJuniorFriendly: false,
    status: "upcoming",
    isFeatured: true,
    isApproved: true,
  },
  {
    slug: "hackathon-social-internacional-2024",
    name: "Hackathon Social Internacional 2024",
    description:
      "Hackathon organizado por Casa Rusa donde equipos diseñan propuestas innovadoras usando metodología Design Sprint. La organización juvenil Hi!Chik de Arequipa ganó el primer lugar con una plataforma de participación ciudadana juvenil.",
    eventType: "hackathon",
    startDate: new Date("2024-11-01T09:00:00"),
    endDate: new Date("2024-11-05T18:00:00"),
    format: "virtual",
    country: "PE",
    city: "Arequipa",
    timezone: "America/Lima",
    skillLevel: "beginner",
    domains: ["social-impact", "mobile", "general"],
    prizePool: 0,
    prizeDescription: "Reconocimiento + visibilidad internacional",
    websiteUrl: "https://senaju.gob.pe",
    registrationUrl: "https://senaju.gob.pe",
    organizerName: "Casa Rusa / SENAJU",
    status: "ended",
    isApproved: true,
  },
  {
    slug: "hackathon-chiclayo-servicios-publicos-2025",
    name: "Hackathon Soluciones Innovadoras - Municipalidad de Chiclayo",
    description:
      "Primera Hackathon de la Municipalidad Provincial de Chiclayo enfocada en soluciones innovadoras para la prestación de servicios públicos. Organizada con el Colegio de Ingenieros del Perú - Consejo Departamental Lambayeque.",
    eventType: "hackathon",
    startDate: new Date("2025-11-15T09:00:00"),
    endDate: new Date("2025-11-17T18:00:00"),
    format: "in-person",
    country: "PE",
    city: "Chiclayo",
    timezone: "America/Lima",
    skillLevel: "all",
    domains: ["govtech", "mobile", "social-impact"],
    prizePool: 0,
    prizeDescription: "Implementación de soluciones ganadoras en servicios municipales",
    websiteUrl: "https://munchiclayo.gob.pe",
    registrationUrl: "https://munchiclayo.gob.pe",
    organizerName: "Municipalidad Provincial de Chiclayo / CIP Lambayeque",
    organizerType: "government",
    isJuniorFriendly: true,
    status: "ended",
    isApproved: true,
  },
  {
    slug: "proof-of-builders-syscoin-hackathon-peru-2025",
    name: "Proof of Builders - Syscoin Hackathon Perú",
    description:
      "Hackathon Web3 donde el código es la llave hacia tu futuro. Onboarding presencial en Universidad Ricardo Palma, mentorías virtuales con Syscoin Foundation. $1,000 USDT en premios.",
    eventType: "hackathon",
    startDate: new Date("2025-11-21T09:00:00"),
    endDate: new Date("2025-12-01T23:59:59"),
    registrationDeadline: new Date("2025-11-20T23:59:59"),
    format: "hybrid",
    country: "PE",
    city: "Lima",
    timezone: "America/Lima",
    skillLevel: "intermediate",
    domains: ["web3", "blockchain"],
    prizePool: 1000,
    prizeDescription: "$1,000 USDT + mentorías oficiales de Syscoin Foundation",
    websiteUrl: "https://horizonteblockchain.org/eventos-web3",
    registrationUrl: "https://horizonteblockchain.org/eventos-web3",
    organizerName: "Horizonte Blockchain / Syscoin Foundation",
    organizerUrl: "https://horizonteblockchain.org",
    status: "ongoing",
    isApproved: true,
  },
  {
    slug: "peru-hub-digital-hackathon-2025",
    name: "Perú Hub Digital Universitario - Hackathon",
    description:
      "Evento que conecta a estudiantes, técnicos y docentes con oportunidades en alta tecnología. Incluye hackathon, torneos de robótica y networking con +50 empresas. Temas: IA, Data Center, Empresa-Universidad.",
    eventType: "conference",
    startDate: new Date("2025-11-14T09:00:00"),
    endDate: new Date("2025-11-15T16:00:00"),
    format: "in-person",
    country: "PE",
    city: "Lima (Escuela Naval)",
    timezone: "America/Lima",
    skillLevel: "all",
    domains: ["ai", "general", "edtech"],
    prizePool: 0,
    prizeDescription: "+30 speakers + zonas interactivas + networking",
    websiteUrl: "https://peruhubdigital.pe",
    registrationUrl: "https://wkf.ms/44sPozS",
    organizerName: "Perú Hub Digital",
    status: "ended",
    isApproved: true,
  },
  {
    slug: "hackathon-economia-circular-produce-2025",
    name: "Hackathon Soluciones Tecnológicas para Economía Circular",
    description:
      "Hackathon de la I Cumbre Produce Circular. Desarrolla soluciones sostenibles para retos de la industria manufacturera y el comercio interno. Con participación de la Embajada de Alemania y apoyo de GIZ.",
    eventType: "hackathon",
    startDate: new Date("2025-10-01T09:00:00"),
    endDate: new Date("2025-10-15T18:00:00"),
    format: "hybrid",
    country: "PE",
    city: "Lima",
    timezone: "America/Lima",
    skillLevel: "intermediate",
    domains: ["climate", "social-impact", "general"],
    prizePool: 0,
    prizeDescription: "Implementación de soluciones + apoyo técnico de GIZ",
    websiteUrl: "https://produce.gob.pe",
    registrationUrl: "https://tinyurl.com/2zhv4atd",
    organizerName: "PRODUCE / Embajada de Alemania / GIZ",
    status: "ended",
    isApproved: true,
  },
  {
    slug: "justihack-peru-2025",
    name: "JustiHack Perú 2025",
    description:
      "Hackathon para proponer soluciones innovadoras que fortalezcan la transparencia, imparcialidad y confianza en el sistema judicial. El equipo de Universidad del Pacífico obtuvo segundo lugar con 'Semáforo Judicial', una plataforma de IA.",
    eventType: "hackathon",
    startDate: new Date("2025-10-27T09:00:00"),
    endDate: new Date("2025-10-27T20:00:00"),
    format: "in-person",
    country: "PE",
    city: "Lima",
    timezone: "America/Lima",
    skillLevel: "intermediate",
    domains: ["ai", "social-impact", "general"],
    prizePool: 0,
    prizeDescription: "Reconocimiento por calidad, innovación, viabilidad y relevancia social",
    websiteUrl: "https://cientifica.edu.pe",
    registrationUrl: "https://cientifica.edu.pe",
    organizerName: "Universidad Científica del Sur",
    status: "ended",
    isApproved: true,
  },
  {
    slug: "nasa-space-apps-peru-2025",
    name: "NASA Space Apps Challenge Perú 2025",
    description:
      "El hackathon internacional más grande del mundo llega a 6 ciudades del Perú: Ayacucho, Arequipa, Cusco, Huancayo, Ica y Lima. Resuelve desafíos reales con datos abiertos de la NASA sobre la Tierra y el espacio.",
    eventType: "hackathon",
    startDate: new Date("2025-10-04T09:00:00"),
    endDate: new Date("2025-10-05T18:00:00"),
    format: "in-person",
    country: "PE",
    city: "Lima, Arequipa, Cusco, Huancayo, Ica, Ayacucho",
    timezone: "America/Lima",
    skillLevel: "all",
    domains: ["ai", "space", "climate"],
    prizePool: 0,
    prizeDescription: "Oportunidad de clasificar a finales globales NASA",
    websiteUrl: "https://www.spaceappschallenge.org",
    registrationUrl: "https://www.spaceappschallenge.org",
    organizerName: "NASA / Universidad Continental",
    organizerType: "international_org",
    organizerUrl: "https://www.continental.edu.pe",
    isJuniorFriendly: true,
    status: "ended",
    isFeatured: true,
    isApproved: true,
  },
  {
    slug: "nasa-space-apps-huanuco-2025",
    name: "NASA Space Apps Challenge Huánuco 2025",
    description:
      "Primera edición oficial del NASA Space Apps Challenge en la región Huánuco. Equipos desarrollaron propuestas de seguridad espacial, plataformas de realidad virtual educativa y sistemas de pronóstico meteorológico con IA.",
    eventType: "hackathon",
    startDate: new Date("2025-10-04T09:00:00"),
    endDate: new Date("2025-10-05T18:00:00"),
    format: "in-person",
    country: "PE",
    city: "Huánuco",
    timezone: "America/Lima",
    skillLevel: "all",
    domains: ["ai", "climate", "edtech"],
    prizePool: 0,
    prizeDescription: "Reconocimiento CIP Huánuco + oportunidad clasificación global",
    websiteUrl: "https://www.spaceappschallenge.org",
    registrationUrl: "https://www.spaceappschallenge.org/2023/locations/huanuco",
    organizerName: "CIP Huánuco / NASA",
    status: "ended",
    isApproved: true,
  },
  {
    slug: "hackathon-quimica-verde-2025",
    name: "II Hackathon de Química Verde",
    description:
      "Desarrolla ideas circulares que integren la química verde con oportunidades sostenibles. Conecta con empresas y mentores nacionales e internacionales de Yale University, ONUDI y MINAM.",
    eventType: "hackathon",
    startDate: new Date("2026-01-20T09:00:00"),
    endDate: new Date("2026-03-15T18:00:00"),
    registrationDeadline: new Date("2026-01-16T23:59:59"),
    format: "hybrid",
    country: "PE",
    city: "Lima",
    timezone: "America/Lima",
    skillLevel: "intermediate",
    domains: ["climate", "general"],
    prizePool: 0,
    prizeDescription: "Posicionamiento nacional e internacional + mentorías Yale/ONUDI",
    websiteUrl: "https://quimicaverde.pe/2dahackathon/",
    registrationUrl: "https://quimicaverde.pe/2dahackathon/",
    organizerName: "Grupo GEA / Yale University / ONUDI / MINAM",
    status: "upcoming",
    isApproved: true,
  },
  {
    slug: "conasein-hackathon-cientifica-2025",
    name: "CONASEIN 2025 - Hackathon Científica",
    description:
      "III Congreso Nacional de Semilleros de Investigación. Incluye proyectos, pósters de investigación, talleres, ponencias y una Hackathon Científica. Reúne estudiantes de universidades públicas y privadas.",
    eventType: "research_fair",
    startDate: new Date("2025-09-24T09:00:00"),
    endDate: new Date("2025-09-26T18:00:00"),
    format: "in-person",
    country: "PE",
    city: "Huancayo",
    timezone: "America/Lima",
    skillLevel: "beginner",
    domains: ["general", "edtech", "healthtech"],
    prizePool: 0,
    prizeDescription: "Reconocimiento académico + networking con investigadores",
    websiteUrl: "https://investigacion.uncp.edu.pe/conasein-2025/",
    registrationUrl: "https://investigacion.uncp.edu.pe/conasein-2025/",
    organizerName: "CONCYTEC / UNCP",
    organizerType: "government",
    organizerUrl: "https://www.concytec.gob.pe",
    isJuniorFriendly: true,
    status: "ended",
    isApproved: true,
  },
  {
    slug: "energ-ia-hackathon-ulima-2025",
    name: "ENERG-IA: Innovación Energética 2025",
    description:
      "Hackathon nacional para estudiantes de pregrado y jóvenes profesionales que quieren revolucionar la energía. Aprende de expertos de AWS, Microsoft, Edulink y Oracle sobre IA y herramientas tecnológicas.",
    eventType: "hackathon",
    startDate: new Date("2025-11-10T09:00:00"),
    endDate: new Date("2025-11-12T18:00:00"),
    format: "hybrid",
    country: "PE",
    city: "Lima",
    timezone: "America/Lima",
    skillLevel: "intermediate",
    domains: ["ai", "climate", "general"],
    prizePool: 8000,
    prizeDescription: "Hasta S/. 8,000 en premios + mentorías AWS, Microsoft, Oracle",
    websiteUrl: "https://www.ulima.edu.pe",
    registrationUrl: "https://bit.ly/46k1ihE",
    organizerName: "Universidad de Lima / Embajada de EE.UU.",
    organizerUrl: "https://www.ulima.edu.pe",
    status: "ended",
    isFeatured: true,
    isApproved: true,
  },
  {
    slug: "hacklife-pmi-2023",
    name: "HackLife PMI 2023 - Caring Us Edition",
    description:
      "Hackathon de innovación social organizado por PMI Perú. Explora soluciones creativas, aprende de expertos en la industria y conecta con mentes brillantes. Incluye talleres de ideación y construcción de MVP.",
    eventType: "hackathon",
    startDate: new Date("2023-12-02T18:00:00"),
    endDate: new Date("2023-12-09T12:00:00"),
    format: "hybrid",
    country: "PE",
    city: "Lima",
    timezone: "America/Lima",
    skillLevel: "all",
    domains: ["social-impact", "general"],
    prizePool: 0,
    prizeDescription: "Mentorías + networking con expertos PMI",
    websiteUrl: "https://hacklife.lat",
    registrationUrl: "https://hacklife.lat",
    organizerName: "PMI Perú",
    status: "ended",
    isApproved: true,
  },
  */
];

export async function seed() {
  console.log("Seed file is temporarily disabled - needs organization migration");
  return;
  /*
  console.log("Seeding database with LATAM events...");

  try {
    // Insert all events
    const inserted = await db.insert(events).values(seedEvents).returning();
    console.log(`Successfully inserted ${inserted.length} events`);

    return inserted;
  } catch (error) {
    console.error("Error seeding database:", error);
    throw error;
  }
}

// Run seed if executed directly
if (require.main === module) {
  seed()
    .then(() => {
      console.log("Seeding complete!");
      process.exit(0);
    })
    .catch((error) => {
      console.error("Seeding failed:", error);
      process.exit(1);
    });
  */
}
